export type Product = {
  id: number
  name: string
  description: string
  image: string
  category?: string
  tag?: string
  originalPrice?: number
  discountedPrice?: number
  discount?: number
  skinType?: string
}

export type ProductDetail = Product & {
  features: string[]
  specifications: Record<string, string>
}

export const featuredProducts: Product[] = [
  {
    id: 1,
    name: "Serum Vitamin C Dưỡng Sáng Da",
    description: "Làm sáng và đều màu da một cách tự nhiên",
    skinType: "Mọi loại da",
    image: "/vitamin-c-serum.jpg",
    tag: "Bán chạy",
    originalPrice: 850000,
    discountedPrice: 680000,
    discount: 20,
  },
  {
    id: 2,
    name: "Kem Dưỡng Ẩm Chiết Xuất Hoa Hồng",
    description: "Cấp ẩm sâu với chiết xuất hoa hồng hữu cơ",
    skinType: "Da khô",
    image: "/rose-face-cream.jpg",
    tag: "Mới",
    originalPrice: 1200000,
    discountedPrice: 960000,
    discount: 20,
  },
  {
    id: 3,
    name: "Sữa Rửa Mặt Dịu Nhẹ",
    description: "Làm sạch nhẹ nhàng không làm khô da",
    skinType: "Da nhạy cảm",
    image: "/cleansing-foam.jpg",
    tag: "Phổ biến",
    originalPrice: 450000,
    discountedPrice: 360000,
    discount: 20,
  },
  {
    id: 4,
    name: "Son Dưỡng Màu Tự Nhiên",
    description: "Màu nhẹ nhàng với thành phần dưỡng chất",
    skinType: "Mọi loại",
    image: "/lip-tint.jpg",
    tag: "Hữu cơ",
    originalPrice: 320000,
    discountedPrice: 256000,
    discount: 20,
  },
]

export const allProducts: Product[] = [
  {
    id: 1,
    name: "Sữa Rửa Mặt Dịu Nhẹ",
    description: "Làm sạch dịu nhẹ, phù hợp da nhạy cảm",
    image: "/cleansing-foam.jpg",
    category: "Skincare",
    tag: "Best Seller",
    originalPrice: 450000,
    discountedPrice: 360000,
    discount: 20,
  },
  {
    id: 2,
    name: "Serum Vitamin C Dưỡng Sáng",
    description: "Giúp da sáng mịn và đều màu tự nhiên",
    image: "/vitamin-c-serum.jpg",
    category: "Skincare",
    tag: "Best Seller",
    originalPrice: 850000,
    discountedPrice: 680000,
    discount: 20,
  },
  {
    id: 3,
    name: "Kem Dưỡng Ẩm Hoa Hồng",
    description: "Cấp ẩm sâu, da căng mướt rạng rỡ",
    image: "/rose-face-cream.jpg",
    category: "Skincare",
    tag: "New",
    originalPrice: 1200000,
    discountedPrice: 960000,
    discount: 20,
  },
  {
    id: 4,
    name: "Son Dưỡng Màu Tự Nhiên",
    description: "Màu nhẹ nhàng, dưỡng ẩm mềm môi",
    image: "/lip-tint.jpg",
    category: "Makeup",
    tag: "Popular",
    originalPrice: 320000,
    discountedPrice: 256000,
    discount: 20,
  },
  {
    id: 5,
    name: "Tẩy Da Chết Body",
    description: "Loại bỏ tế bào chết, da mịn màng hơn",
    image: "/body-scrub.jpg",
    category: "Body Care",
    tag: "Popular",
    originalPrice: 480000,
    discountedPrice: 384000,
    discount: 20,
  },
  {
    id: 6,
    name: "Bơ Dưỡng Thể",
    description: "Dưỡng ẩm sâu, da mềm mại cả ngày",
    image: "/body-butter.jpg",
    category: "Body Care",
    tag: "Best Seller",
    originalPrice: 550000,
    discountedPrice: 440000,
    discount: 20,
  },
  {
    id: 7,
    name: "Kem Chống Nắng Khoáng",
    description: "Bảo vệ da SPF 50 nhẹ dịu mỗi ngày",
    image: "/sunscreen.jpg",
    category: "Skincare",
    tag: "New",
    originalPrice: 680000,
    discountedPrice: 544000,
    discount: 20,
  },
  {
    id: 8,
    name: "Mặt Nạ Than Hoạt Tính",
    description: "Làm sạch sâu và thông thoáng lỗ chân lông",
    image: "/face-mask.jpg",
    category: "Skincare",
    tag: "Popular",
    originalPrice: 420000,
    discountedPrice: 336000,
    discount: 20,
  },
  {
    id: 9,
    name: "Mascara Hữu Cơ",
    description: "Tạo độ dài và dày tự nhiên cho mi",
    image: "/mascara.jpg",
    category: "Makeup",
    tag: "Vegan",
    originalPrice: 380000,
    discountedPrice: 304000,
    discount: 20,
  },
  {
    id: 10,
    name: "Bảng Phấn Má Hồng",
    description: "Màu sắc tự nhiên, dễ tán đều",
    image: "/blush-palette.jpg",
    category: "Makeup",
    tag: "Best Seller",
    originalPrice: 560000,
    discountedPrice: 448000,
    discount: 20,
  },
  {
    id: 11,
    name: "Dầu Dưỡng Thể Thư Giãn",
    description: "Hương thơm dịu nhẹ, dưỡng ẩm mềm da",
    image: "/body-oil.jpg",
    category: "Body Care",
    tag: "Organic",
    originalPrice: 720000,
    discountedPrice: 576000,
    discount: 20,
  },
  {
    id: 12,
    name: "Kem Dưỡng Mắt",
    description: "Giảm quầng thâm, làm mịn vùng mắt",
    image: "/eye-cream.jpg",
    category: "Skincare",
    tag: "New",
    originalPrice: 920000,
    discountedPrice: 736000,
    discount: 20,
  },
  {
    id: 13,
    name: "Vitamin C Brightening Serum",
    description: "Illuminates and evens skin tone naturally",
    image: "/vitamin-c-serum.jpg",
    category: "Skincare",
    tag: "Best Seller",
    originalPrice: 850000,
    discountedPrice: 680000,
    discount: 20,
  },
  {
    id: 14,
    name: "Hydrating Rose Face Cream",
    description: "Deep moisture with organic rose extract",
    image: "/rose-face-cream.jpg",
    category: "Skincare",
    tag: "New",
    originalPrice: 1200000,
    discountedPrice: 960000,
    discount: 20,
  },
  {
    id: 15,
    name: "Gentle Cleansing Foam",
    description: "Purifies without stripping natural oils",
    image: "/cleansing-foam.jpg",
    category: "Skincare",
    tag: "Popular",
    originalPrice: 450000,
    discountedPrice: 360000,
    discount: 20,
  },
  {
    id: 16,
    name: "Natural Glow Lip Tint",
    description: "Subtle color with nourishing ingredients",
    image: "/lip-tint.jpg",
    category: "Makeup",
    tag: "Organic",
    originalPrice: 320000,
    discountedPrice: 256000,
    discount: 20,
  },
  {
    id: 17,
    name: "Nourishing Body Butter",
    description: "Rich hydration for soft, smooth skin",
    image: "/body-butter.jpg",
    category: "Body Care",
    tag: "Best Seller",
    originalPrice: 550000,
    discountedPrice: 440000,
    discount: 20,
  },
  {
    id: 18,
    name: "Mineral Sunscreen SPF 50",
    description: "Lightweight protection with natural minerals",
    image: "/sunscreen.jpg",
    category: "Skincare",
    tag: "New",
    originalPrice: 680000,
    discountedPrice: 544000,
    discount: 20,
  },
  {
    id: 19,
    name: "Charcoal Face Mask",
    description: "Deeply cleanses and detoxifies pores",
    image: "/face-mask.jpg",
    category: "Skincare",
    tag: "Popular",
    originalPrice: 420000,
    discountedPrice: 336000,
    discount: 20,
  },
  {
    id: 20,
    name: "Organic Mascara",
    description: "Lengthens and volumizes naturally",
    image: "/mascara.jpg",
    category: "Makeup",
    tag: "Vegan",
    originalPrice: 380000,
    discountedPrice: 304000,
    discount: 20,
  },
  {
    id: 21,
    name: "Exfoliating Body Scrub",
    description: "Gently buffs away dead skin cells",
    image: "/body-scrub.jpg",
    category: "Body Care",
    tag: "Popular",
    originalPrice: 480000,
    discountedPrice: 384000,
    discount: 20,
  },
  {
    id: 22,
    name: "Rejuvenating Eye Cream",
    description: "Reduces dark circles and fine lines",
    image: "/eye-cream.jpg",
    category: "Skincare",
    tag: "New",
    originalPrice: 920000,
    discountedPrice: 736000,
    discount: 20,
  },
  {
    id: 23,
    name: "Natural Blush Palette",
    description: "Soft, buildable color for a healthy glow",
    image: "/blush-palette.jpg",
    category: "Makeup",
    tag: "Best Seller",
    originalPrice: 560000,
    discountedPrice: 448000,
    discount: 20,
  },
  {
    id: 24,
    name: "Aromatherapy Body Oil",
    description: "Luxurious oil with calming essential oils",
    image: "/body-oil.jpg",
    category: "Body Care",
    tag: "Organic",
    originalPrice: 720000,
    discountedPrice: 576000,
    discount: 20,
  },
]

export const productsData: Record<string, ProductDetail> = {
  "1": {
    id: 1,
    name: "Vitamin C Brightening Serum",
    description:
      "This powerful serum is formulated with 15% pure Vitamin C to brighten and even your skin tone. The lightweight formula absorbs quickly, delivering potent antioxidants deep into your skin. Perfect for all skin types, it helps reduce dark spots and promotes a radiant, youthful glow.",
    image: "/vitamin-c-serum.jpg",
    category: "Skincare",
    tag: "Best Seller",
    originalPrice: 850000,
    discountedPrice: 680000,
    discount: 20,
    features: [
      "15% Pure Vitamin C for maximum effectiveness",
      "Brightens and evens skin tone naturally",
      "Reduces appearance of dark spots and hyperpigmentation",
      "Lightweight, fast-absorbing formula",
      "Suitable for all skin types including sensitive skin",
    ],
    specifications: {
      "Key Ingredients": "Vitamin C, Hyaluronic Acid, Vitamin E",
      Volume: "30ml",
      "Skin Type": "All skin types",
      "How to Use": "Apply 2-3 drops to clean face morning and evening",
    },
  },
  "2": {
    id: 2,
    name: "Hydrating Rose Face Cream",
    description:
      "Indulge your skin with this luxurious face cream infused with organic rose extract. The rich, creamy formula provides deep hydration while soothing and nourishing dry skin. Wake up to plump, dewy, and radiant skin every morning.",
    image: "/rose-face-cream.jpg",
    category: "Skincare",
    tag: "New",
    originalPrice: 1200000,
    discountedPrice: 960000,
    discount: 20,
    features: [
      "Infused with organic Damascus rose extract",
      "Provides 24-hour deep hydration",
      "Nourishes and softens dry skin",
      "Anti-aging properties reduce fine lines",
      "Delicate natural rose scent",
    ],
    specifications: {
      "Key Ingredients": "Rose Extract, Shea Butter, Jojoba Oil",
      Volume: "50ml",
      "Skin Type": "Dry and mature skin",
      "How to Use": "Apply to clean face morning and night",
    },
  },
  "3": {
    id: 3,
    name: "Gentle Cleansing Foam",
    description:
      "Start your skincare routine with this gentle cleansing foam that purifies your skin without stripping its natural oils. The soft, creamy lather removes makeup, dirt, and impurities while maintaining your skin's moisture balance.",
    image: "/cleansing-foam.jpg",
    category: "Skincare",
    tag: "Popular",
    originalPrice: 450000,
    discountedPrice: 360000,
    discount: 20,
    features: [
      "Gentle formula for sensitive skin",
      "Removes makeup and impurities effectively",
      "Maintains skin's natural moisture balance",
      "Contains soothing chamomile extract",
      "pH-balanced for healthy skin",
    ],
    specifications: {
      "Key Ingredients": "Chamomile, Aloe Vera, Glycerin",
      Volume: "150ml",
      "Skin Type": "Sensitive and normal skin",
      "How to Use": "Massage onto damp face, rinse thoroughly",
    },
  },
  "4": {
    id: 4,
    name: "Natural Glow Lip Tint",
    description:
      "Achieve the perfect natural lip look with this nourishing lip tint. The lightweight formula provides a subtle wash of color while keeping your lips soft and hydrated throughout the day. Made with organic ingredients for guilt-free beauty.",
    image: "/lip-tint.jpg",
    category: "Makeup",
    tag: "Organic",
    originalPrice: 320000,
    discountedPrice: 256000,
    discount: 20,
    features: [
      "Subtle, buildable color for natural look",
      "Infused with nourishing plant oils",
      "Long-lasting hydration",
      "100% organic and vegan ingredients",
      "Available in 4 flattering shades",
    ],
    specifications: {
      "Key Ingredients": "Jojoba Oil, Vitamin E, Natural Pigments",
      Volume: "4g",
      "Skin Type": "All types",
      "How to Use": "Apply directly to lips, build for more intensity",
    },
  },
}

export const getProductById = (id: string | number) => productsData[String(id)]
